version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s | %(levelname)-7s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stderr

loggers:
  aps_acc:
    level: INFO
    handlers: [console]
    propagate: false
  urllib3:
    level: WARNING
  requests:
    level: WARNING

root:
  level: WARNING
  handlers: [console]
